// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reference_line_smoother_config.proto

#include "reference_line_smoother_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_cos_5ftheta_5fsmoother_5fconfig_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_cos_5ftheta_5fsmoother_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CosThetaSmootherConfig;
}  // namespace protobuf_cos_5ftheta_5fsmoother_5fconfig_2eproto
namespace protobuf_fem_5fpos_5fdeviation_5fsmoother_5fconfig_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_fem_5fpos_5fdeviation_5fsmoother_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_FemPosDeviationSmootherConfig;
}  // namespace protobuf_fem_5fpos_5fdeviation_5fsmoother_5fconfig_2eproto
namespace protobuf_reference_5fline_5fsmoother_5fconfig_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_reference_5fline_5fsmoother_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_QpSplineSmootherConfig;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_reference_5fline_5fsmoother_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SpiralSmootherConfig;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_reference_5fline_5fsmoother_5fconfig_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_DiscretePointsSmootherConfig;
}  // namespace protobuf_reference_5fline_5fsmoother_5fconfig_2eproto
namespace apollo {
namespace planning {
class QpSplineSmootherConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<QpSplineSmootherConfig>
      _instance;
} _QpSplineSmootherConfig_default_instance_;
class SpiralSmootherConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SpiralSmootherConfig>
      _instance;
} _SpiralSmootherConfig_default_instance_;
class DiscretePointsSmootherConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DiscretePointsSmootherConfig>
      _instance;
  const ::apollo::planning::CosThetaSmootherConfig* cos_theta_smoothing_;
  const ::apollo::planning::FemPosDeviationSmootherConfig* fem_pos_deviation_smoothing_;
} _DiscretePointsSmootherConfig_default_instance_;
class ReferenceLineSmootherConfigDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ReferenceLineSmootherConfig>
      _instance;
  const ::apollo::planning::QpSplineSmootherConfig* qp_spline_;
  const ::apollo::planning::SpiralSmootherConfig* spiral_;
  const ::apollo::planning::DiscretePointsSmootherConfig* discrete_points_;
} _ReferenceLineSmootherConfig_default_instance_;
}  // namespace planning
}  // namespace apollo
namespace protobuf_reference_5fline_5fsmoother_5fconfig_2eproto {
static void InitDefaultsQpSplineSmootherConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::planning::_QpSplineSmootherConfig_default_instance_;
    new (ptr) ::apollo::planning::QpSplineSmootherConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::planning::QpSplineSmootherConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_QpSplineSmootherConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsQpSplineSmootherConfig}, {}};

static void InitDefaultsSpiralSmootherConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::planning::_SpiralSmootherConfig_default_instance_;
    new (ptr) ::apollo::planning::SpiralSmootherConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::planning::SpiralSmootherConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SpiralSmootherConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSpiralSmootherConfig}, {}};

static void InitDefaultsDiscretePointsSmootherConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::planning::_DiscretePointsSmootherConfig_default_instance_;
    new (ptr) ::apollo::planning::DiscretePointsSmootherConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::planning::DiscretePointsSmootherConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_DiscretePointsSmootherConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsDiscretePointsSmootherConfig}, {
      &protobuf_cos_5ftheta_5fsmoother_5fconfig_2eproto::scc_info_CosThetaSmootherConfig.base,
      &protobuf_fem_5fpos_5fdeviation_5fsmoother_5fconfig_2eproto::scc_info_FemPosDeviationSmootherConfig.base,}};

static void InitDefaultsReferenceLineSmootherConfig() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::apollo::planning::_ReferenceLineSmootherConfig_default_instance_;
    new (ptr) ::apollo::planning::ReferenceLineSmootherConfig();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::apollo::planning::ReferenceLineSmootherConfig::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_ReferenceLineSmootherConfig =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsReferenceLineSmootherConfig}, {
      &protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_QpSplineSmootherConfig.base,
      &protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_SpiralSmootherConfig.base,
      &protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_DiscretePointsSmootherConfig.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_QpSplineSmootherConfig.base);
  ::google::protobuf::internal::InitSCC(&scc_info_SpiralSmootherConfig.base);
  ::google::protobuf::internal::InitSCC(&scc_info_DiscretePointsSmootherConfig.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ReferenceLineSmootherConfig.base);
}

::google::protobuf::Metadata file_level_metadata[4];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::QpSplineSmootherConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::QpSplineSmootherConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::QpSplineSmootherConfig, spline_order_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::QpSplineSmootherConfig, max_spline_length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::QpSplineSmootherConfig, regularization_weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::QpSplineSmootherConfig, second_derivative_weight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::QpSplineSmootherConfig, third_derivative_weight_),
  1,
  2,
  3,
  0,
  4,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, max_deviation_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, piecewise_length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, max_iteration_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, opt_tol_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, opt_acceptable_tol_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, opt_acceptable_iteration_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, weight_curve_length_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, weight_kappa_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::SpiralSmootherConfig, weight_dkappa_),
  0,
  1,
  3,
  2,
  5,
  4,
  6,
  7,
  8,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::DiscretePointsSmootherConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::DiscretePointsSmootherConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::DiscretePointsSmootherConfig, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::DiscretePointsSmootherConfig, smoothing_method_),
  offsetof(::apollo::planning::DiscretePointsSmootherConfigDefaultTypeInternal, cos_theta_smoothing_),
  offsetof(::apollo::planning::DiscretePointsSmootherConfigDefaultTypeInternal, fem_pos_deviation_smoothing_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::DiscretePointsSmootherConfig, SmootherConfig_),
  0,
  ~0u,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, max_constraint_interval_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, longitudinal_boundary_bound_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, max_lateral_boundary_bound_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, min_lateral_boundary_bound_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, num_of_total_points_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, curb_shift_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, lateral_buffer_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, resolution_),
  offsetof(::apollo::planning::ReferenceLineSmootherConfigDefaultTypeInternal, qp_spline_),
  offsetof(::apollo::planning::ReferenceLineSmootherConfigDefaultTypeInternal, spiral_),
  offsetof(::apollo::planning::ReferenceLineSmootherConfigDefaultTypeInternal, discrete_points_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::apollo::planning::ReferenceLineSmootherConfig, SmootherConfig_),
  1,
  2,
  3,
  4,
  0,
  5,
  6,
  7,
  ~0u,
  ~0u,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 10, sizeof(::apollo::planning::QpSplineSmootherConfig)},
  { 15, 29, sizeof(::apollo::planning::SpiralSmootherConfig)},
  { 38, 47, sizeof(::apollo::planning::DiscretePointsSmootherConfig)},
  { 50, 67, sizeof(::apollo::planning::ReferenceLineSmootherConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::planning::_QpSplineSmootherConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::planning::_SpiralSmootherConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::planning::_DiscretePointsSmootherConfig_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::apollo::planning::_ReferenceLineSmootherConfig_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "reference_line_smoother_config.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n$reference_line_smoother_config.proto\022\017"
      "apollo.planning\032\037cos_theta_smoother_conf"
      "ig.proto\032\'fem_pos_deviation_smoother_con"
      "fig.proto\"\277\001\n\026QpSplineSmootherConfig\022\027\n\014"
      "spline_order\030\001 \001(\r:\0015\022\035\n\021max_spline_leng"
      "th\030\002 \001(\001:\00225\022\"\n\025regularization_weight\030\003 "
      "\001(\001:\0030.1\022#\n\030second_derivative_weight\030\004 \001"
      "(\001:\0010\022$\n\027third_derivative_weight\030\005 \001(\001:\003"
      "100\"\243\002\n\024SpiralSmootherConfig\022\032\n\rmax_devi"
      "ation\030\001 \001(\001:\0030.1\022\034\n\020piecewise_length\030\002 \001"
      "(\001:\00210\022\033\n\rmax_iteration\030\003 \001(\r:\0041000\022\026\n\007o"
      "pt_tol\030\004 \001(\001:\0051e-08\022!\n\022opt_acceptable_to"
      "l\030\005 \001(\001:\0051e-06\022$\n\030opt_acceptable_iterati"
      "on\030\006 \001(\r:\00215\022\036\n\023weight_curve_length\030\007 \001("
      "\001:\0011\022\027\n\014weight_kappa\030\010 \001(\001:\0011\022\032\n\rweight_"
      "dkappa\030\t \001(\001:\003100\"\243\003\n\034DiscretePointsSmoo"
      "therConfig\022t\n\020smoothing_method\030\003 \001(\0162=.a"
      "pollo.planning.DiscretePointsSmootherCon"
      "fig.SmoothingMethod:\033FEM_POS_DEVIATION_S"
      "MOOTHING\022F\n\023cos_theta_smoothing\030\004 \001(\0132\'."
      "apollo.planning.CosThetaSmootherConfigH\000"
      "\022U\n\033fem_pos_deviation_smoothing\030\005 \001(\0132.."
      "apollo.planning.FemPosDeviationSmootherC"
      "onfigH\000\"\\\n\017SmoothingMethod\022\017\n\013NOT_DEFINE"
      "D\020\000\022\027\n\023COS_THETA_SMOOTHING\020\001\022\037\n\033FEM_POS_"
      "DEVIATION_SMOOTHING\020\002B\020\n\016SmootherConfig\""
      "\200\004\n\033ReferenceLineSmootherConfig\022\"\n\027max_c"
      "onstraint_interval\030\001 \001(\001:\0015\022&\n\033longitudi"
      "nal_boundary_bound\030\002 \001(\001:\0011\022\'\n\032max_later"
      "al_boundary_bound\030\003 \001(\001:\0030.5\022\'\n\032min_late"
      "ral_boundary_bound\030\004 \001(\001:\0030.2\022 \n\023num_of_"
      "total_points\030\005 \001(\r:\003500\022\027\n\ncurb_shift\030\006 "
      "\001(\001:\0030.2\022\033\n\016lateral_buffer\030\007 \001(\001:\0030.2\022\030\n"
      "\nresolution\030\010 \001(\001:\0040.02\022<\n\tqp_spline\030\024 \001"
      "(\0132\'.apollo.planning.QpSplineSmootherCon"
      "figH\000\0227\n\006spiral\030\025 \001(\0132%.apollo.planning."
      "SpiralSmootherConfigH\000\022H\n\017discrete_point"
      "s\030\026 \001(\0132-.apollo.planning.DiscretePoints"
      "SmootherConfigH\000B\020\n\016SmootherConfig"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1554);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "reference_line_smoother_config.proto", &protobuf_RegisterTypes);
  ::protobuf_cos_5ftheta_5fsmoother_5fconfig_2eproto::AddDescriptors();
  ::protobuf_fem_5fpos_5fdeviation_5fsmoother_5fconfig_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_reference_5fline_5fsmoother_5fconfig_2eproto
namespace apollo {
namespace planning {
const ::google::protobuf::EnumDescriptor* DiscretePointsSmootherConfig_SmoothingMethod_descriptor() {
  protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::file_level_enum_descriptors[0];
}
bool DiscretePointsSmootherConfig_SmoothingMethod_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const DiscretePointsSmootherConfig_SmoothingMethod DiscretePointsSmootherConfig::NOT_DEFINED;
const DiscretePointsSmootherConfig_SmoothingMethod DiscretePointsSmootherConfig::COS_THETA_SMOOTHING;
const DiscretePointsSmootherConfig_SmoothingMethod DiscretePointsSmootherConfig::FEM_POS_DEVIATION_SMOOTHING;
const DiscretePointsSmootherConfig_SmoothingMethod DiscretePointsSmootherConfig::SmoothingMethod_MIN;
const DiscretePointsSmootherConfig_SmoothingMethod DiscretePointsSmootherConfig::SmoothingMethod_MAX;
const int DiscretePointsSmootherConfig::SmoothingMethod_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void QpSplineSmootherConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int QpSplineSmootherConfig::kSplineOrderFieldNumber;
const int QpSplineSmootherConfig::kMaxSplineLengthFieldNumber;
const int QpSplineSmootherConfig::kRegularizationWeightFieldNumber;
const int QpSplineSmootherConfig::kSecondDerivativeWeightFieldNumber;
const int QpSplineSmootherConfig::kThirdDerivativeWeightFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

QpSplineSmootherConfig::QpSplineSmootherConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_QpSplineSmootherConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.planning.QpSplineSmootherConfig)
}
QpSplineSmootherConfig::QpSplineSmootherConfig(const QpSplineSmootherConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&second_derivative_weight_, &from.second_derivative_weight_,
    static_cast<size_t>(reinterpret_cast<char*>(&third_derivative_weight_) -
    reinterpret_cast<char*>(&second_derivative_weight_)) + sizeof(third_derivative_weight_));
  // @@protoc_insertion_point(copy_constructor:apollo.planning.QpSplineSmootherConfig)
}

void QpSplineSmootherConfig::SharedCtor() {
  second_derivative_weight_ = 0;
  spline_order_ = 5u;
  max_spline_length_ = 25;
  regularization_weight_ = 0.1;
  third_derivative_weight_ = 100;
}

QpSplineSmootherConfig::~QpSplineSmootherConfig() {
  // @@protoc_insertion_point(destructor:apollo.planning.QpSplineSmootherConfig)
  SharedDtor();
}

void QpSplineSmootherConfig::SharedDtor() {
}

void QpSplineSmootherConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* QpSplineSmootherConfig::descriptor() {
  ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const QpSplineSmootherConfig& QpSplineSmootherConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_QpSplineSmootherConfig.base);
  return *internal_default_instance();
}


void QpSplineSmootherConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.planning.QpSplineSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 31u) {
    second_derivative_weight_ = 0;
    spline_order_ = 5u;
    max_spline_length_ = 25;
    regularization_weight_ = 0.1;
    third_derivative_weight_ = 100;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool QpSplineSmootherConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.planning.QpSplineSmootherConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 spline_order = 1 [default = 5];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_spline_order();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &spline_order_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double max_spline_length = 2 [default = 25];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_max_spline_length();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &max_spline_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double regularization_weight = 3 [default = 0.1];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {
          set_has_regularization_weight();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &regularization_weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double second_derivative_weight = 4 [default = 0];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {
          set_has_second_derivative_weight();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &second_derivative_weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double third_derivative_weight = 5 [default = 100];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {
          set_has_third_derivative_weight();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &third_derivative_weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.planning.QpSplineSmootherConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.planning.QpSplineSmootherConfig)
  return false;
#undef DO_
}

void QpSplineSmootherConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.planning.QpSplineSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 spline_order = 1 [default = 5];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->spline_order(), output);
  }

  // optional double max_spline_length = 2 [default = 25];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->max_spline_length(), output);
  }

  // optional double regularization_weight = 3 [default = 0.1];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->regularization_weight(), output);
  }

  // optional double second_derivative_weight = 4 [default = 0];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->second_derivative_weight(), output);
  }

  // optional double third_derivative_weight = 5 [default = 100];
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->third_derivative_weight(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.planning.QpSplineSmootherConfig)
}

::google::protobuf::uint8* QpSplineSmootherConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.planning.QpSplineSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 spline_order = 1 [default = 5];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->spline_order(), target);
  }

  // optional double max_spline_length = 2 [default = 25];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->max_spline_length(), target);
  }

  // optional double regularization_weight = 3 [default = 0.1];
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->regularization_weight(), target);
  }

  // optional double second_derivative_weight = 4 [default = 0];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->second_derivative_weight(), target);
  }

  // optional double third_derivative_weight = 5 [default = 100];
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->third_derivative_weight(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.planning.QpSplineSmootherConfig)
  return target;
}

size_t QpSplineSmootherConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.planning.QpSplineSmootherConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 31u) {
    // optional double second_derivative_weight = 4 [default = 0];
    if (has_second_derivative_weight()) {
      total_size += 1 + 8;
    }

    // optional uint32 spline_order = 1 [default = 5];
    if (has_spline_order()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->spline_order());
    }

    // optional double max_spline_length = 2 [default = 25];
    if (has_max_spline_length()) {
      total_size += 1 + 8;
    }

    // optional double regularization_weight = 3 [default = 0.1];
    if (has_regularization_weight()) {
      total_size += 1 + 8;
    }

    // optional double third_derivative_weight = 5 [default = 100];
    if (has_third_derivative_weight()) {
      total_size += 1 + 8;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void QpSplineSmootherConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.planning.QpSplineSmootherConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const QpSplineSmootherConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const QpSplineSmootherConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.planning.QpSplineSmootherConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.planning.QpSplineSmootherConfig)
    MergeFrom(*source);
  }
}

void QpSplineSmootherConfig::MergeFrom(const QpSplineSmootherConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.planning.QpSplineSmootherConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 31u) {
    if (cached_has_bits & 0x00000001u) {
      second_derivative_weight_ = from.second_derivative_weight_;
    }
    if (cached_has_bits & 0x00000002u) {
      spline_order_ = from.spline_order_;
    }
    if (cached_has_bits & 0x00000004u) {
      max_spline_length_ = from.max_spline_length_;
    }
    if (cached_has_bits & 0x00000008u) {
      regularization_weight_ = from.regularization_weight_;
    }
    if (cached_has_bits & 0x00000010u) {
      third_derivative_weight_ = from.third_derivative_weight_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void QpSplineSmootherConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.planning.QpSplineSmootherConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void QpSplineSmootherConfig::CopyFrom(const QpSplineSmootherConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.planning.QpSplineSmootherConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool QpSplineSmootherConfig::IsInitialized() const {
  return true;
}

void QpSplineSmootherConfig::Swap(QpSplineSmootherConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void QpSplineSmootherConfig::InternalSwap(QpSplineSmootherConfig* other) {
  using std::swap;
  swap(second_derivative_weight_, other->second_derivative_weight_);
  swap(spline_order_, other->spline_order_);
  swap(max_spline_length_, other->max_spline_length_);
  swap(regularization_weight_, other->regularization_weight_);
  swap(third_derivative_weight_, other->third_derivative_weight_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata QpSplineSmootherConfig::GetMetadata() const {
  protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void SpiralSmootherConfig::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SpiralSmootherConfig::kMaxDeviationFieldNumber;
const int SpiralSmootherConfig::kPiecewiseLengthFieldNumber;
const int SpiralSmootherConfig::kMaxIterationFieldNumber;
const int SpiralSmootherConfig::kOptTolFieldNumber;
const int SpiralSmootherConfig::kOptAcceptableTolFieldNumber;
const int SpiralSmootherConfig::kOptAcceptableIterationFieldNumber;
const int SpiralSmootherConfig::kWeightCurveLengthFieldNumber;
const int SpiralSmootherConfig::kWeightKappaFieldNumber;
const int SpiralSmootherConfig::kWeightDkappaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SpiralSmootherConfig::SpiralSmootherConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_SpiralSmootherConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.planning.SpiralSmootherConfig)
}
SpiralSmootherConfig::SpiralSmootherConfig(const SpiralSmootherConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&max_deviation_, &from.max_deviation_,
    static_cast<size_t>(reinterpret_cast<char*>(&weight_dkappa_) -
    reinterpret_cast<char*>(&max_deviation_)) + sizeof(weight_dkappa_));
  // @@protoc_insertion_point(copy_constructor:apollo.planning.SpiralSmootherConfig)
}

void SpiralSmootherConfig::SharedCtor() {
  max_deviation_ = 0.1;
  piecewise_length_ = 10;
  opt_tol_ = 1e-08;
  max_iteration_ = 1000u;
  opt_acceptable_iteration_ = 15u;
  opt_acceptable_tol_ = 1e-06;
  weight_curve_length_ = 1;
  weight_kappa_ = 1;
  weight_dkappa_ = 100;
}

SpiralSmootherConfig::~SpiralSmootherConfig() {
  // @@protoc_insertion_point(destructor:apollo.planning.SpiralSmootherConfig)
  SharedDtor();
}

void SpiralSmootherConfig::SharedDtor() {
}

void SpiralSmootherConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SpiralSmootherConfig::descriptor() {
  ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SpiralSmootherConfig& SpiralSmootherConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_SpiralSmootherConfig.base);
  return *internal_default_instance();
}


void SpiralSmootherConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.planning.SpiralSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 255u) {
    max_deviation_ = 0.1;
    piecewise_length_ = 10;
    opt_tol_ = 1e-08;
    max_iteration_ = 1000u;
    opt_acceptable_iteration_ = 15u;
    opt_acceptable_tol_ = 1e-06;
    weight_curve_length_ = 1;
    weight_kappa_ = 1;
  }
  weight_dkappa_ = 100;
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool SpiralSmootherConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.planning.SpiralSmootherConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double max_deviation = 1 [default = 0.1];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_max_deviation();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &max_deviation_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double piecewise_length = 2 [default = 10];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_piecewise_length();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &piecewise_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 max_iteration = 3 [default = 1000];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          set_has_max_iteration();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &max_iteration_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double opt_tol = 4 [default = 1e-08];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {
          set_has_opt_tol();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &opt_tol_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double opt_acceptable_tol = 5 [default = 1e-06];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {
          set_has_opt_acceptable_tol();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &opt_acceptable_tol_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 opt_acceptable_iteration = 6 [default = 15];
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          set_has_opt_acceptable_iteration();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &opt_acceptable_iteration_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double weight_curve_length = 7 [default = 1];
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u /* 57 & 0xFF */)) {
          set_has_weight_curve_length();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &weight_curve_length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double weight_kappa = 8 [default = 1];
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(65u /* 65 & 0xFF */)) {
          set_has_weight_kappa();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &weight_kappa_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double weight_dkappa = 9 [default = 100];
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(73u /* 73 & 0xFF */)) {
          set_has_weight_dkappa();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &weight_dkappa_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.planning.SpiralSmootherConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.planning.SpiralSmootherConfig)
  return false;
#undef DO_
}

void SpiralSmootherConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.planning.SpiralSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double max_deviation = 1 [default = 0.1];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->max_deviation(), output);
  }

  // optional double piecewise_length = 2 [default = 10];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->piecewise_length(), output);
  }

  // optional uint32 max_iteration = 3 [default = 1000];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->max_iteration(), output);
  }

  // optional double opt_tol = 4 [default = 1e-08];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->opt_tol(), output);
  }

  // optional double opt_acceptable_tol = 5 [default = 1e-06];
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->opt_acceptable_tol(), output);
  }

  // optional uint32 opt_acceptable_iteration = 6 [default = 15];
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->opt_acceptable_iteration(), output);
  }

  // optional double weight_curve_length = 7 [default = 1];
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->weight_curve_length(), output);
  }

  // optional double weight_kappa = 8 [default = 1];
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->weight_kappa(), output);
  }

  // optional double weight_dkappa = 9 [default = 100];
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->weight_dkappa(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.planning.SpiralSmootherConfig)
}

::google::protobuf::uint8* SpiralSmootherConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.planning.SpiralSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double max_deviation = 1 [default = 0.1];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->max_deviation(), target);
  }

  // optional double piecewise_length = 2 [default = 10];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->piecewise_length(), target);
  }

  // optional uint32 max_iteration = 3 [default = 1000];
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->max_iteration(), target);
  }

  // optional double opt_tol = 4 [default = 1e-08];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->opt_tol(), target);
  }

  // optional double opt_acceptable_tol = 5 [default = 1e-06];
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->opt_acceptable_tol(), target);
  }

  // optional uint32 opt_acceptable_iteration = 6 [default = 15];
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->opt_acceptable_iteration(), target);
  }

  // optional double weight_curve_length = 7 [default = 1];
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->weight_curve_length(), target);
  }

  // optional double weight_kappa = 8 [default = 1];
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->weight_kappa(), target);
  }

  // optional double weight_dkappa = 9 [default = 100];
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->weight_dkappa(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.planning.SpiralSmootherConfig)
  return target;
}

size_t SpiralSmootherConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.planning.SpiralSmootherConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 255u) {
    // optional double max_deviation = 1 [default = 0.1];
    if (has_max_deviation()) {
      total_size += 1 + 8;
    }

    // optional double piecewise_length = 2 [default = 10];
    if (has_piecewise_length()) {
      total_size += 1 + 8;
    }

    // optional double opt_tol = 4 [default = 1e-08];
    if (has_opt_tol()) {
      total_size += 1 + 8;
    }

    // optional uint32 max_iteration = 3 [default = 1000];
    if (has_max_iteration()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->max_iteration());
    }

    // optional uint32 opt_acceptable_iteration = 6 [default = 15];
    if (has_opt_acceptable_iteration()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->opt_acceptable_iteration());
    }

    // optional double opt_acceptable_tol = 5 [default = 1e-06];
    if (has_opt_acceptable_tol()) {
      total_size += 1 + 8;
    }

    // optional double weight_curve_length = 7 [default = 1];
    if (has_weight_curve_length()) {
      total_size += 1 + 8;
    }

    // optional double weight_kappa = 8 [default = 1];
    if (has_weight_kappa()) {
      total_size += 1 + 8;
    }

  }
  // optional double weight_dkappa = 9 [default = 100];
  if (has_weight_dkappa()) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SpiralSmootherConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.planning.SpiralSmootherConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const SpiralSmootherConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SpiralSmootherConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.planning.SpiralSmootherConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.planning.SpiralSmootherConfig)
    MergeFrom(*source);
  }
}

void SpiralSmootherConfig::MergeFrom(const SpiralSmootherConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.planning.SpiralSmootherConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      max_deviation_ = from.max_deviation_;
    }
    if (cached_has_bits & 0x00000002u) {
      piecewise_length_ = from.piecewise_length_;
    }
    if (cached_has_bits & 0x00000004u) {
      opt_tol_ = from.opt_tol_;
    }
    if (cached_has_bits & 0x00000008u) {
      max_iteration_ = from.max_iteration_;
    }
    if (cached_has_bits & 0x00000010u) {
      opt_acceptable_iteration_ = from.opt_acceptable_iteration_;
    }
    if (cached_has_bits & 0x00000020u) {
      opt_acceptable_tol_ = from.opt_acceptable_tol_;
    }
    if (cached_has_bits & 0x00000040u) {
      weight_curve_length_ = from.weight_curve_length_;
    }
    if (cached_has_bits & 0x00000080u) {
      weight_kappa_ = from.weight_kappa_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  if (cached_has_bits & 0x00000100u) {
    set_weight_dkappa(from.weight_dkappa());
  }
}

void SpiralSmootherConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.planning.SpiralSmootherConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SpiralSmootherConfig::CopyFrom(const SpiralSmootherConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.planning.SpiralSmootherConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SpiralSmootherConfig::IsInitialized() const {
  return true;
}

void SpiralSmootherConfig::Swap(SpiralSmootherConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SpiralSmootherConfig::InternalSwap(SpiralSmootherConfig* other) {
  using std::swap;
  swap(max_deviation_, other->max_deviation_);
  swap(piecewise_length_, other->piecewise_length_);
  swap(opt_tol_, other->opt_tol_);
  swap(max_iteration_, other->max_iteration_);
  swap(opt_acceptable_iteration_, other->opt_acceptable_iteration_);
  swap(opt_acceptable_tol_, other->opt_acceptable_tol_);
  swap(weight_curve_length_, other->weight_curve_length_);
  swap(weight_kappa_, other->weight_kappa_);
  swap(weight_dkappa_, other->weight_dkappa_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SpiralSmootherConfig::GetMetadata() const {
  protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DiscretePointsSmootherConfig::InitAsDefaultInstance() {
  ::apollo::planning::_DiscretePointsSmootherConfig_default_instance_.cos_theta_smoothing_ = const_cast< ::apollo::planning::CosThetaSmootherConfig*>(
      ::apollo::planning::CosThetaSmootherConfig::internal_default_instance());
  ::apollo::planning::_DiscretePointsSmootherConfig_default_instance_.fem_pos_deviation_smoothing_ = const_cast< ::apollo::planning::FemPosDeviationSmootherConfig*>(
      ::apollo::planning::FemPosDeviationSmootherConfig::internal_default_instance());
}
void DiscretePointsSmootherConfig::set_allocated_cos_theta_smoothing(::apollo::planning::CosThetaSmootherConfig* cos_theta_smoothing) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_SmootherConfig();
  if (cos_theta_smoothing) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      cos_theta_smoothing = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, cos_theta_smoothing, submessage_arena);
    }
    set_has_cos_theta_smoothing();
    SmootherConfig_.cos_theta_smoothing_ = cos_theta_smoothing;
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.DiscretePointsSmootherConfig.cos_theta_smoothing)
}
void DiscretePointsSmootherConfig::clear_cos_theta_smoothing() {
  if (has_cos_theta_smoothing()) {
    delete SmootherConfig_.cos_theta_smoothing_;
    clear_has_SmootherConfig();
  }
}
void DiscretePointsSmootherConfig::set_allocated_fem_pos_deviation_smoothing(::apollo::planning::FemPosDeviationSmootherConfig* fem_pos_deviation_smoothing) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_SmootherConfig();
  if (fem_pos_deviation_smoothing) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      fem_pos_deviation_smoothing = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, fem_pos_deviation_smoothing, submessage_arena);
    }
    set_has_fem_pos_deviation_smoothing();
    SmootherConfig_.fem_pos_deviation_smoothing_ = fem_pos_deviation_smoothing;
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.DiscretePointsSmootherConfig.fem_pos_deviation_smoothing)
}
void DiscretePointsSmootherConfig::clear_fem_pos_deviation_smoothing() {
  if (has_fem_pos_deviation_smoothing()) {
    delete SmootherConfig_.fem_pos_deviation_smoothing_;
    clear_has_SmootherConfig();
  }
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DiscretePointsSmootherConfig::kSmoothingMethodFieldNumber;
const int DiscretePointsSmootherConfig::kCosThetaSmoothingFieldNumber;
const int DiscretePointsSmootherConfig::kFemPosDeviationSmoothingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DiscretePointsSmootherConfig::DiscretePointsSmootherConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_DiscretePointsSmootherConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.planning.DiscretePointsSmootherConfig)
}
DiscretePointsSmootherConfig::DiscretePointsSmootherConfig(const DiscretePointsSmootherConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  smoothing_method_ = from.smoothing_method_;
  clear_has_SmootherConfig();
  switch (from.SmootherConfig_case()) {
    case kCosThetaSmoothing: {
      mutable_cos_theta_smoothing()->::apollo::planning::CosThetaSmootherConfig::MergeFrom(from.cos_theta_smoothing());
      break;
    }
    case kFemPosDeviationSmoothing: {
      mutable_fem_pos_deviation_smoothing()->::apollo::planning::FemPosDeviationSmootherConfig::MergeFrom(from.fem_pos_deviation_smoothing());
      break;
    }
    case SMOOTHERCONFIG_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:apollo.planning.DiscretePointsSmootherConfig)
}

void DiscretePointsSmootherConfig::SharedCtor() {
  smoothing_method_ = 2;
  clear_has_SmootherConfig();
}

DiscretePointsSmootherConfig::~DiscretePointsSmootherConfig() {
  // @@protoc_insertion_point(destructor:apollo.planning.DiscretePointsSmootherConfig)
  SharedDtor();
}

void DiscretePointsSmootherConfig::SharedDtor() {
  if (has_SmootherConfig()) {
    clear_SmootherConfig();
  }
}

void DiscretePointsSmootherConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* DiscretePointsSmootherConfig::descriptor() {
  ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DiscretePointsSmootherConfig& DiscretePointsSmootherConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_DiscretePointsSmootherConfig.base);
  return *internal_default_instance();
}


void DiscretePointsSmootherConfig::clear_SmootherConfig() {
// @@protoc_insertion_point(one_of_clear_start:apollo.planning.DiscretePointsSmootherConfig)
  switch (SmootherConfig_case()) {
    case kCosThetaSmoothing: {
      delete SmootherConfig_.cos_theta_smoothing_;
      break;
    }
    case kFemPosDeviationSmoothing: {
      delete SmootherConfig_.fem_pos_deviation_smoothing_;
      break;
    }
    case SMOOTHERCONFIG_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = SMOOTHERCONFIG_NOT_SET;
}


void DiscretePointsSmootherConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.planning.DiscretePointsSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  smoothing_method_ = 2;
  clear_SmootherConfig();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool DiscretePointsSmootherConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.planning.DiscretePointsSmootherConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .apollo.planning.DiscretePointsSmootherConfig.SmoothingMethod smoothing_method = 3 [default = FEM_POS_DEVIATION_SMOOTHING];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::apollo::planning::DiscretePointsSmootherConfig_SmoothingMethod_IsValid(value)) {
            set_smoothing_method(static_cast< ::apollo::planning::DiscretePointsSmootherConfig_SmoothingMethod >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                3, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.planning.CosThetaSmootherConfig cos_theta_smoothing = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_cos_theta_smoothing()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.planning.FemPosDeviationSmootherConfig fem_pos_deviation_smoothing = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_fem_pos_deviation_smoothing()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.planning.DiscretePointsSmootherConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.planning.DiscretePointsSmootherConfig)
  return false;
#undef DO_
}

void DiscretePointsSmootherConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.planning.DiscretePointsSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .apollo.planning.DiscretePointsSmootherConfig.SmoothingMethod smoothing_method = 3 [default = FEM_POS_DEVIATION_SMOOTHING];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->smoothing_method(), output);
  }

  switch (SmootherConfig_case()) {
    case kCosThetaSmoothing:
      ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
        4, this->_internal_cos_theta_smoothing(), output);
      break;
    case kFemPosDeviationSmoothing:
      ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
        5, this->_internal_fem_pos_deviation_smoothing(), output);
      break;
    default: ;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.planning.DiscretePointsSmootherConfig)
}

::google::protobuf::uint8* DiscretePointsSmootherConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.planning.DiscretePointsSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .apollo.planning.DiscretePointsSmootherConfig.SmoothingMethod smoothing_method = 3 [default = FEM_POS_DEVIATION_SMOOTHING];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->smoothing_method(), target);
  }

  switch (SmootherConfig_case()) {
    case kCosThetaSmoothing:
      target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessageToArray(
          4, this->_internal_cos_theta_smoothing(), deterministic, target);
      break;
    case kFemPosDeviationSmoothing:
      target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessageToArray(
          5, this->_internal_fem_pos_deviation_smoothing(), deterministic, target);
      break;
    default: ;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.planning.DiscretePointsSmootherConfig)
  return target;
}

size_t DiscretePointsSmootherConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.planning.DiscretePointsSmootherConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // optional .apollo.planning.DiscretePointsSmootherConfig.SmoothingMethod smoothing_method = 3 [default = FEM_POS_DEVIATION_SMOOTHING];
  if (has_smoothing_method()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->smoothing_method());
  }

  switch (SmootherConfig_case()) {
    // optional .apollo.planning.CosThetaSmootherConfig cos_theta_smoothing = 4;
    case kCosThetaSmoothing: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *SmootherConfig_.cos_theta_smoothing_);
      break;
    }
    // optional .apollo.planning.FemPosDeviationSmootherConfig fem_pos_deviation_smoothing = 5;
    case kFemPosDeviationSmoothing: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *SmootherConfig_.fem_pos_deviation_smoothing_);
      break;
    }
    case SMOOTHERCONFIG_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void DiscretePointsSmootherConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.planning.DiscretePointsSmootherConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const DiscretePointsSmootherConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DiscretePointsSmootherConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.planning.DiscretePointsSmootherConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.planning.DiscretePointsSmootherConfig)
    MergeFrom(*source);
  }
}

void DiscretePointsSmootherConfig::MergeFrom(const DiscretePointsSmootherConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.planning.DiscretePointsSmootherConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_smoothing_method()) {
    set_smoothing_method(from.smoothing_method());
  }
  switch (from.SmootherConfig_case()) {
    case kCosThetaSmoothing: {
      mutable_cos_theta_smoothing()->::apollo::planning::CosThetaSmootherConfig::MergeFrom(from.cos_theta_smoothing());
      break;
    }
    case kFemPosDeviationSmoothing: {
      mutable_fem_pos_deviation_smoothing()->::apollo::planning::FemPosDeviationSmootherConfig::MergeFrom(from.fem_pos_deviation_smoothing());
      break;
    }
    case SMOOTHERCONFIG_NOT_SET: {
      break;
    }
  }
}

void DiscretePointsSmootherConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.planning.DiscretePointsSmootherConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DiscretePointsSmootherConfig::CopyFrom(const DiscretePointsSmootherConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.planning.DiscretePointsSmootherConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DiscretePointsSmootherConfig::IsInitialized() const {
  return true;
}

void DiscretePointsSmootherConfig::Swap(DiscretePointsSmootherConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DiscretePointsSmootherConfig::InternalSwap(DiscretePointsSmootherConfig* other) {
  using std::swap;
  swap(smoothing_method_, other->smoothing_method_);
  swap(SmootherConfig_, other->SmootherConfig_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata DiscretePointsSmootherConfig::GetMetadata() const {
  protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ReferenceLineSmootherConfig::InitAsDefaultInstance() {
  ::apollo::planning::_ReferenceLineSmootherConfig_default_instance_.qp_spline_ = const_cast< ::apollo::planning::QpSplineSmootherConfig*>(
      ::apollo::planning::QpSplineSmootherConfig::internal_default_instance());
  ::apollo::planning::_ReferenceLineSmootherConfig_default_instance_.spiral_ = const_cast< ::apollo::planning::SpiralSmootherConfig*>(
      ::apollo::planning::SpiralSmootherConfig::internal_default_instance());
  ::apollo::planning::_ReferenceLineSmootherConfig_default_instance_.discrete_points_ = const_cast< ::apollo::planning::DiscretePointsSmootherConfig*>(
      ::apollo::planning::DiscretePointsSmootherConfig::internal_default_instance());
}
void ReferenceLineSmootherConfig::set_allocated_qp_spline(::apollo::planning::QpSplineSmootherConfig* qp_spline) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_SmootherConfig();
  if (qp_spline) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      qp_spline = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, qp_spline, submessage_arena);
    }
    set_has_qp_spline();
    SmootherConfig_.qp_spline_ = qp_spline;
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.ReferenceLineSmootherConfig.qp_spline)
}
void ReferenceLineSmootherConfig::set_allocated_spiral(::apollo::planning::SpiralSmootherConfig* spiral) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_SmootherConfig();
  if (spiral) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      spiral = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, spiral, submessage_arena);
    }
    set_has_spiral();
    SmootherConfig_.spiral_ = spiral;
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.ReferenceLineSmootherConfig.spiral)
}
void ReferenceLineSmootherConfig::set_allocated_discrete_points(::apollo::planning::DiscretePointsSmootherConfig* discrete_points) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_SmootherConfig();
  if (discrete_points) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      discrete_points = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, discrete_points, submessage_arena);
    }
    set_has_discrete_points();
    SmootherConfig_.discrete_points_ = discrete_points;
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.planning.ReferenceLineSmootherConfig.discrete_points)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReferenceLineSmootherConfig::kMaxConstraintIntervalFieldNumber;
const int ReferenceLineSmootherConfig::kLongitudinalBoundaryBoundFieldNumber;
const int ReferenceLineSmootherConfig::kMaxLateralBoundaryBoundFieldNumber;
const int ReferenceLineSmootherConfig::kMinLateralBoundaryBoundFieldNumber;
const int ReferenceLineSmootherConfig::kNumOfTotalPointsFieldNumber;
const int ReferenceLineSmootherConfig::kCurbShiftFieldNumber;
const int ReferenceLineSmootherConfig::kLateralBufferFieldNumber;
const int ReferenceLineSmootherConfig::kResolutionFieldNumber;
const int ReferenceLineSmootherConfig::kQpSplineFieldNumber;
const int ReferenceLineSmootherConfig::kSpiralFieldNumber;
const int ReferenceLineSmootherConfig::kDiscretePointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReferenceLineSmootherConfig::ReferenceLineSmootherConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_ReferenceLineSmootherConfig.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:apollo.planning.ReferenceLineSmootherConfig)
}
ReferenceLineSmootherConfig::ReferenceLineSmootherConfig(const ReferenceLineSmootherConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&num_of_total_points_, &from.num_of_total_points_,
    static_cast<size_t>(reinterpret_cast<char*>(&resolution_) -
    reinterpret_cast<char*>(&num_of_total_points_)) + sizeof(resolution_));
  clear_has_SmootherConfig();
  switch (from.SmootherConfig_case()) {
    case kQpSpline: {
      mutable_qp_spline()->::apollo::planning::QpSplineSmootherConfig::MergeFrom(from.qp_spline());
      break;
    }
    case kSpiral: {
      mutable_spiral()->::apollo::planning::SpiralSmootherConfig::MergeFrom(from.spiral());
      break;
    }
    case kDiscretePoints: {
      mutable_discrete_points()->::apollo::planning::DiscretePointsSmootherConfig::MergeFrom(from.discrete_points());
      break;
    }
    case SMOOTHERCONFIG_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:apollo.planning.ReferenceLineSmootherConfig)
}

void ReferenceLineSmootherConfig::SharedCtor() {
  num_of_total_points_ = 500u;
  max_constraint_interval_ = 5;
  longitudinal_boundary_bound_ = 1;
  max_lateral_boundary_bound_ = 0.5;
  min_lateral_boundary_bound_ = 0.2;
  curb_shift_ = 0.2;
  lateral_buffer_ = 0.2;
  resolution_ = 0.02;
  clear_has_SmootherConfig();
}

ReferenceLineSmootherConfig::~ReferenceLineSmootherConfig() {
  // @@protoc_insertion_point(destructor:apollo.planning.ReferenceLineSmootherConfig)
  SharedDtor();
}

void ReferenceLineSmootherConfig::SharedDtor() {
  if (has_SmootherConfig()) {
    clear_SmootherConfig();
  }
}

void ReferenceLineSmootherConfig::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ReferenceLineSmootherConfig::descriptor() {
  ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ReferenceLineSmootherConfig& ReferenceLineSmootherConfig::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::scc_info_ReferenceLineSmootherConfig.base);
  return *internal_default_instance();
}


void ReferenceLineSmootherConfig::clear_SmootherConfig() {
// @@protoc_insertion_point(one_of_clear_start:apollo.planning.ReferenceLineSmootherConfig)
  switch (SmootherConfig_case()) {
    case kQpSpline: {
      delete SmootherConfig_.qp_spline_;
      break;
    }
    case kSpiral: {
      delete SmootherConfig_.spiral_;
      break;
    }
    case kDiscretePoints: {
      delete SmootherConfig_.discrete_points_;
      break;
    }
    case SMOOTHERCONFIG_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = SMOOTHERCONFIG_NOT_SET;
}


void ReferenceLineSmootherConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:apollo.planning.ReferenceLineSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 255u) {
    num_of_total_points_ = 500u;
    max_constraint_interval_ = 5;
    longitudinal_boundary_bound_ = 1;
    max_lateral_boundary_bound_ = 0.5;
    min_lateral_boundary_bound_ = 0.2;
    curb_shift_ = 0.2;
    lateral_buffer_ = 0.2;
    resolution_ = 0.02;
  }
  clear_SmootherConfig();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool ReferenceLineSmootherConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:apollo.planning.ReferenceLineSmootherConfig)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double max_constraint_interval = 1 [default = 5];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_max_constraint_interval();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &max_constraint_interval_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double longitudinal_boundary_bound = 2 [default = 1];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_longitudinal_boundary_bound();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &longitudinal_boundary_bound_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double max_lateral_boundary_bound = 3 [default = 0.5];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {
          set_has_max_lateral_boundary_bound();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &max_lateral_boundary_bound_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double min_lateral_boundary_bound = 4 [default = 0.2];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {
          set_has_min_lateral_boundary_bound();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &min_lateral_boundary_bound_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 num_of_total_points = 5 [default = 500];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          set_has_num_of_total_points();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &num_of_total_points_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double curb_shift = 6 [default = 0.2];
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(49u /* 49 & 0xFF */)) {
          set_has_curb_shift();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &curb_shift_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double lateral_buffer = 7 [default = 0.2];
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(57u /* 57 & 0xFF */)) {
          set_has_lateral_buffer();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lateral_buffer_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double resolution = 8 [default = 0.02];
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(65u /* 65 & 0xFF */)) {
          set_has_resolution();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &resolution_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.planning.QpSplineSmootherConfig qp_spline = 20;
      case 20: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(162u /* 162 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_qp_spline()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.planning.SpiralSmootherConfig spiral = 21;
      case 21: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(170u /* 170 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_spiral()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .apollo.planning.DiscretePointsSmootherConfig discrete_points = 22;
      case 22: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(178u /* 178 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_discrete_points()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:apollo.planning.ReferenceLineSmootherConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:apollo.planning.ReferenceLineSmootherConfig)
  return false;
#undef DO_
}

void ReferenceLineSmootherConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:apollo.planning.ReferenceLineSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double max_constraint_interval = 1 [default = 5];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->max_constraint_interval(), output);
  }

  // optional double longitudinal_boundary_bound = 2 [default = 1];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->longitudinal_boundary_bound(), output);
  }

  // optional double max_lateral_boundary_bound = 3 [default = 0.5];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->max_lateral_boundary_bound(), output);
  }

  // optional double min_lateral_boundary_bound = 4 [default = 0.2];
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->min_lateral_boundary_bound(), output);
  }

  // optional uint32 num_of_total_points = 5 [default = 500];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->num_of_total_points(), output);
  }

  // optional double curb_shift = 6 [default = 0.2];
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->curb_shift(), output);
  }

  // optional double lateral_buffer = 7 [default = 0.2];
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->lateral_buffer(), output);
  }

  // optional double resolution = 8 [default = 0.02];
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->resolution(), output);
  }

  switch (SmootherConfig_case()) {
    case kQpSpline:
      ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
        20, this->_internal_qp_spline(), output);
      break;
    case kSpiral:
      ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
        21, this->_internal_spiral(), output);
      break;
    case kDiscretePoints:
      ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
        22, this->_internal_discrete_points(), output);
      break;
    default: ;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:apollo.planning.ReferenceLineSmootherConfig)
}

::google::protobuf::uint8* ReferenceLineSmootherConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:apollo.planning.ReferenceLineSmootherConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double max_constraint_interval = 1 [default = 5];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->max_constraint_interval(), target);
  }

  // optional double longitudinal_boundary_bound = 2 [default = 1];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->longitudinal_boundary_bound(), target);
  }

  // optional double max_lateral_boundary_bound = 3 [default = 0.5];
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->max_lateral_boundary_bound(), target);
  }

  // optional double min_lateral_boundary_bound = 4 [default = 0.2];
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->min_lateral_boundary_bound(), target);
  }

  // optional uint32 num_of_total_points = 5 [default = 500];
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->num_of_total_points(), target);
  }

  // optional double curb_shift = 6 [default = 0.2];
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->curb_shift(), target);
  }

  // optional double lateral_buffer = 7 [default = 0.2];
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->lateral_buffer(), target);
  }

  // optional double resolution = 8 [default = 0.02];
  if (cached_has_bits & 0x00000080u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->resolution(), target);
  }

  switch (SmootherConfig_case()) {
    case kQpSpline:
      target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessageToArray(
          20, this->_internal_qp_spline(), deterministic, target);
      break;
    case kSpiral:
      target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessageToArray(
          21, this->_internal_spiral(), deterministic, target);
      break;
    case kDiscretePoints:
      target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessageToArray(
          22, this->_internal_discrete_points(), deterministic, target);
      break;
    default: ;
  }
  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:apollo.planning.ReferenceLineSmootherConfig)
  return target;
}

size_t ReferenceLineSmootherConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:apollo.planning.ReferenceLineSmootherConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 255u) {
    // optional uint32 num_of_total_points = 5 [default = 500];
    if (has_num_of_total_points()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->num_of_total_points());
    }

    // optional double max_constraint_interval = 1 [default = 5];
    if (has_max_constraint_interval()) {
      total_size += 1 + 8;
    }

    // optional double longitudinal_boundary_bound = 2 [default = 1];
    if (has_longitudinal_boundary_bound()) {
      total_size += 1 + 8;
    }

    // optional double max_lateral_boundary_bound = 3 [default = 0.5];
    if (has_max_lateral_boundary_bound()) {
      total_size += 1 + 8;
    }

    // optional double min_lateral_boundary_bound = 4 [default = 0.2];
    if (has_min_lateral_boundary_bound()) {
      total_size += 1 + 8;
    }

    // optional double curb_shift = 6 [default = 0.2];
    if (has_curb_shift()) {
      total_size += 1 + 8;
    }

    // optional double lateral_buffer = 7 [default = 0.2];
    if (has_lateral_buffer()) {
      total_size += 1 + 8;
    }

    // optional double resolution = 8 [default = 0.02];
    if (has_resolution()) {
      total_size += 1 + 8;
    }

  }
  switch (SmootherConfig_case()) {
    // optional .apollo.planning.QpSplineSmootherConfig qp_spline = 20;
    case kQpSpline: {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *SmootherConfig_.qp_spline_);
      break;
    }
    // optional .apollo.planning.SpiralSmootherConfig spiral = 21;
    case kSpiral: {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *SmootherConfig_.spiral_);
      break;
    }
    // optional .apollo.planning.DiscretePointsSmootherConfig discrete_points = 22;
    case kDiscretePoints: {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *SmootherConfig_.discrete_points_);
      break;
    }
    case SMOOTHERCONFIG_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ReferenceLineSmootherConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:apollo.planning.ReferenceLineSmootherConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const ReferenceLineSmootherConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReferenceLineSmootherConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:apollo.planning.ReferenceLineSmootherConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:apollo.planning.ReferenceLineSmootherConfig)
    MergeFrom(*source);
  }
}

void ReferenceLineSmootherConfig::MergeFrom(const ReferenceLineSmootherConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:apollo.planning.ReferenceLineSmootherConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      num_of_total_points_ = from.num_of_total_points_;
    }
    if (cached_has_bits & 0x00000002u) {
      max_constraint_interval_ = from.max_constraint_interval_;
    }
    if (cached_has_bits & 0x00000004u) {
      longitudinal_boundary_bound_ = from.longitudinal_boundary_bound_;
    }
    if (cached_has_bits & 0x00000008u) {
      max_lateral_boundary_bound_ = from.max_lateral_boundary_bound_;
    }
    if (cached_has_bits & 0x00000010u) {
      min_lateral_boundary_bound_ = from.min_lateral_boundary_bound_;
    }
    if (cached_has_bits & 0x00000020u) {
      curb_shift_ = from.curb_shift_;
    }
    if (cached_has_bits & 0x00000040u) {
      lateral_buffer_ = from.lateral_buffer_;
    }
    if (cached_has_bits & 0x00000080u) {
      resolution_ = from.resolution_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  switch (from.SmootherConfig_case()) {
    case kQpSpline: {
      mutable_qp_spline()->::apollo::planning::QpSplineSmootherConfig::MergeFrom(from.qp_spline());
      break;
    }
    case kSpiral: {
      mutable_spiral()->::apollo::planning::SpiralSmootherConfig::MergeFrom(from.spiral());
      break;
    }
    case kDiscretePoints: {
      mutable_discrete_points()->::apollo::planning::DiscretePointsSmootherConfig::MergeFrom(from.discrete_points());
      break;
    }
    case SMOOTHERCONFIG_NOT_SET: {
      break;
    }
  }
}

void ReferenceLineSmootherConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:apollo.planning.ReferenceLineSmootherConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReferenceLineSmootherConfig::CopyFrom(const ReferenceLineSmootherConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:apollo.planning.ReferenceLineSmootherConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReferenceLineSmootherConfig::IsInitialized() const {
  return true;
}

void ReferenceLineSmootherConfig::Swap(ReferenceLineSmootherConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReferenceLineSmootherConfig::InternalSwap(ReferenceLineSmootherConfig* other) {
  using std::swap;
  swap(num_of_total_points_, other->num_of_total_points_);
  swap(max_constraint_interval_, other->max_constraint_interval_);
  swap(longitudinal_boundary_bound_, other->longitudinal_boundary_bound_);
  swap(max_lateral_boundary_bound_, other->max_lateral_boundary_bound_);
  swap(min_lateral_boundary_bound_, other->min_lateral_boundary_bound_);
  swap(curb_shift_, other->curb_shift_);
  swap(lateral_buffer_, other->lateral_buffer_);
  swap(resolution_, other->resolution_);
  swap(SmootherConfig_, other->SmootherConfig_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ReferenceLineSmootherConfig::GetMetadata() const {
  protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_reference_5fline_5fsmoother_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace planning
}  // namespace apollo
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::planning::QpSplineSmootherConfig* Arena::CreateMaybeMessage< ::apollo::planning::QpSplineSmootherConfig >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::planning::QpSplineSmootherConfig >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::planning::SpiralSmootherConfig* Arena::CreateMaybeMessage< ::apollo::planning::SpiralSmootherConfig >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::planning::SpiralSmootherConfig >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::planning::DiscretePointsSmootherConfig* Arena::CreateMaybeMessage< ::apollo::planning::DiscretePointsSmootherConfig >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::planning::DiscretePointsSmootherConfig >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::apollo::planning::ReferenceLineSmootherConfig* Arena::CreateMaybeMessage< ::apollo::planning::ReferenceLineSmootherConfig >(Arena* arena) {
  return Arena::CreateInternal< ::apollo::planning::ReferenceLineSmootherConfig >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
